version: '3.7'

services:
  app:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/usr/node/app
    depends_on:
      - database_ignite
    links:
      - database_ignite

  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - ./.docker/db:/data/postgres
